function fail (details){
  console.log(details);
  errbreak = true;
}
